services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: easytravel
      POSTGRES_DB: easytravel
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: easy-travel-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: easytravel
      POSTGRES_DB: easytravel

volumes:
  postgres-data:
